export default [
  {
    title: "Eye Mesh Boat Shoes",
    price: "220.00",
    rate: "best",
    categories: "",
    image: "../images/product/img1.jpg",
    color: "blue",
    size: "s",
  },
  {
    title: "Blue Raincoat Shoes",
    price: "430.00",
    rate: "sale",
    image: "../images/product/img1.jpg",
    color: "grey",
    size: "m",
  },
  {
    title: "Tailored indigo jumpsuit ",
    price: "128.00",
    rate: "sale",
    image: "../images/product/img1.jpg",
    color: "black",
    size: "xs",
  },
  {
    title: "Triple stone drop earrings",
    price: "49.50",
    rate: "sale",
    image: "../images/product/img1.jpg",
    color: "white",
    size: "l",
  },
  {
    title: "Backpack with contrast",
    price: "158.00",
    rate: "new",
    image: "../images/product/img1.jpg",
    color: "blue",
    size: "xl",
  },
  {
    title: "Eye Mesh Boat Shoes",
    price: "220.00",
    rate: "best",
    image: "../images/product/img1.jpg",
    color: "grey",
    size: "4xl",
  },
  {
    title: "Azure Tote Shoes Boat",
    price: "290.00",
    rate: "new",
    image: "../images/product/img1.jpg",
    color: "black",
    size: "3xl",
  },
  {
    title: "Backpack with contrast",
    price: "80.00",
    rate: "sale",
    image: "../images/product/img1.jpg",
    color: "grey",
    size: "2xl",
  },
  {
    title: "Shirt in organic cotton ",
    price: "59.50",
    rate: "best",
    image: "../images/product/img1.jpg",
    color: "yellow",
    size: "M",
  },
  {
    title: "Tailored indigo jumpsuit ",
    price: "128.00",
    rate: "sale",
    image: "../images/product/img1.jpg",
    color: "blue",
    size: "s",
  },
  {
    title: "Eye Mesh Boat Shoes",
    price: "220.00",
    rate: "new",
    image: "../images/product/img1.jpg",
    color: "black",
    size: "2xl",
  },
  {
    title: "Azure Tote Shoes Boat",
    price: "290.00",
    rate: "best",
    image: "../images/product/img1.jpg",
    color: "white",
    size: "3xl",
  },
  {
    title: "Blue Raincoat Shoes",
    price: "430.00",
    rate: "new",
    image: "../images/product/img1.jpg",
    color: "yellow",
    size: "xs",
  },
  {
    title: "Triple stone drop earrings",
    price: "49.50",
    rate: "sale",
    image: "../images/product/img1.jpg",
    color: "blue",
    size: "s",
  },
  {
    title: "Backpack with contrast",
    price: "158.00",
    rate: "best",
    image: "../images/product/img1.jpg",
    color: "black",
    size: "l",
  },
  {
    title: "Eye Mesh Boat Shoes",
    price: "220.00",
    rate: "new",
    image: "../images/product/img1.jpg",
    color: "white",
    size: "4xl",
  },
  {
    title: "Azure Tote Shoes Boat",
    price: "290.00",
    rate: "best",
    image: "../images/product/img1.jpg",
    color: "yellow",
    size: "xs",
  },
  {
    title: "Blue Raincoat Shoes",
    price: "430.00",
    rate: "new",
    image: "../images/product/img1.jpg",
    color: "yellow",
    size: "xs",
  },
  {
    title: "Triple stone drop earrings",
    price: "49.50",
    rate: "sale",
    image: "../images/product/img1.jpg",
    color: "blue",
    size: "s",
  },
  {
    title: "Backpack with contrast",
    price: "158.00",
    rate: "best",
    image: "../images/product/img1.jpg",
    color: "black",
    size: "l",
  },
  {
    title: "Eye Mesh Boat Shoes",
    price: "220.00",
    rate: "new",
    image: "../images/product/img1.jpg",
    color: "white",
    size: "4xl",
  },
  {
    title: "Azure Tote Shoes Boat",
    price: "290.00",
    rate: "best",
    image: "../images/product/img1.jpg",
    color: "yellow",
    size: "xs",
  },
];
